version: "2"
services:
  acme-fe:
    build: ./acme-fe
    ports: 
      - '1234:1234'
    depends_on:
      - acme-api
  acme-api:
    build: ./acme-api
    ports:
      - "8080:8080"
    depends_on:
      - broker-api
      - mongo
  broker-api:
    build: ./broker-api
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
